<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/work_leave.proto

namespace Work_leave;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>work_leave.Employee</code>
 */
class Employee extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 employee_id = 1;</code>
     */
    protected $employee_id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>float accrued_leave_days = 3;</code>
     */
    protected $accrued_leave_days = 0.0;
    /**
     * Generated from protobuf field <code>float requested_leave_days = 4;</code>
     */
    protected $requested_leave_days = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $employee_id
     *     @type string $name
     *     @type float $accrued_leave_days
     *     @type float $requested_leave_days
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\WorkLeave::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 employee_id = 1;</code>
     * @return int
     */
    public function getEmployeeId()
    {
        return $this->employee_id;
    }

    /**
     * Generated from protobuf field <code>int32 employee_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEmployeeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->employee_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float accrued_leave_days = 3;</code>
     * @return float
     */
    public function getAccruedLeaveDays()
    {
        return $this->accrued_leave_days;
    }

    /**
     * Generated from protobuf field <code>float accrued_leave_days = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAccruedLeaveDays($var)
    {
        GPBUtil::checkFloat($var);
        $this->accrued_leave_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float requested_leave_days = 4;</code>
     * @return float
     */
    public function getRequestedLeaveDays()
    {
        return $this->requested_leave_days;
    }

    /**
     * Generated from protobuf field <code>float requested_leave_days = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setRequestedLeaveDays($var)
    {
        GPBUtil::checkFloat($var);
        $this->requested_leave_days = $var;

        return $this;
    }

}

