<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/work_leave.proto

namespace Work_leave;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>work_leave.LeaveEligibility</code>
 */
class LeaveEligibility extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool eligible = 1;</code>
     */
    protected $eligible = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $eligible
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\WorkLeave::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool eligible = 1;</code>
     * @return bool
     */
    public function getEligible()
    {
        return $this->eligible;
    }

    /**
     * Generated from protobuf field <code>bool eligible = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEligible($var)
    {
        GPBUtil::checkBool($var);
        $this->eligible = $var;

        return $this;
    }

}

