<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/work_leave.proto

namespace Work_leave;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>work_leave.LeaveFeedback</code>
 */
class LeaveFeedback extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool granted = 1;</code>
     */
    protected $granted = false;
    /**
     * Generated from protobuf field <code>float accrued_leave_days = 2;</code>
     */
    protected $accrued_leave_days = 0.0;
    /**
     * Generated from protobuf field <code>float granted_leave_days = 3;</code>
     */
    protected $granted_leave_days = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $granted
     *     @type float $accrued_leave_days
     *     @type float $granted_leave_days
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\WorkLeave::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool granted = 1;</code>
     * @return bool
     */
    public function getGranted()
    {
        return $this->granted;
    }

    /**
     * Generated from protobuf field <code>bool granted = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setGranted($var)
    {
        GPBUtil::checkBool($var);
        $this->granted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float accrued_leave_days = 2;</code>
     * @return float
     */
    public function getAccruedLeaveDays()
    {
        return $this->accrued_leave_days;
    }

    /**
     * Generated from protobuf field <code>float accrued_leave_days = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAccruedLeaveDays($var)
    {
        GPBUtil::checkFloat($var);
        $this->accrued_leave_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float granted_leave_days = 3;</code>
     * @return float
     */
    public function getGrantedLeaveDays()
    {
        return $this->granted_leave_days;
    }

    /**
     * Generated from protobuf field <code>float granted_leave_days = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setGrantedLeaveDays($var)
    {
        GPBUtil::checkFloat($var);
        $this->granted_leave_days = $var;

        return $this;
    }

}

